unique_ids:
  assets:
    standard-page.html: 6BDLNDXZZHSAYOQLKAZFFW7ZNH6D4JLY
    theme.css: UI3CBGOESADEM7NQNSUM5VI6UEQCFVMA
  forms:
    AccountComponent: EVIMTXOSC4EGYXHCDX6B44EQUHS3TZRX
    AddMeasurementComponent: 6JP72KYIFY5JPWBBHT7WHNYIHSTKTW6L
    CompareComponent: C6V3H6PTCWDCOSNCPRFKBFRLV3WV5NRN
    HomeAnonComponent: 2N2GKI5ZVJIK4DRQWUPZBK5Q5T5QYQNL
    HomeDetailsComponent: BE54ZKIVQJOHRF4SS3KWVELTQV5HWXLJ
    HomeForm: 5HVWPBGZFUHEP3GPA7IPMIX7TC6YPS4T
    SetHeightComponent: NMCFU4OYNFB64BGK6ZUU5FAXCBGMSQUH
  modules:
    data_access: BQX7AU5Q3ILELWNX7HPTFL6LPJWNEEVC
    navigation: OBYMSV6CDB5ANAEZQTR7RNIBSAICO36B
  scripts: {}
  server_modules:
    api: TZ2BRMVOW4LBE55YP55UOCQG2ET2HQ7S
    auth: BGWEEO52KERNZ33MY3HA2B4JSLHCGWA5
    data_loader: LBISVPDADD76BQBHHAW6MG37JMHSACFV
    measurement_service: ECVAO4L5RVSGDBCGPXWHVM6QWWIMEPYH
